---
name: 'Publish Collection to Ansible Galaxy'

on: # yamllint disable-line rule:truthy
  pull_request:
    branches: ["main", "stable", "release/v*"]
  push:
    branches:
      - 'main'
  workflow_dispatch: {}

jobs:
  lint:
    name: 'Run ansible-lint'
    runs-on: 'ubuntu-latest'
    steps:
      - name: checkout
        uses: actions/checkout@v4
        # with:
        #   path: "${{ github.repository }}"

      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        # # optional (see below):
        with:
          args: ""
          setup_python: "true"
          working_directory: ""
          requirements_file: ""
  test:
    name: 'Run molecule tests'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Set up Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip
          pip install molecule molecule-plugins[docker] ansible

      - name: 'Run molecule'
        run: |
          molecule test

  publish:
    name: 'Publish Collection to Ansible Galaxy'
    needs:
      - lint
      - test
    runs-on: 'ubuntu-latest'
    if: github.ref == 'refs/heads/main'
    steps:
      - name: 'Checkout code'
        uses: 'actions/checkout@v4'

      - name: 'Build and Deploy Collection'
        uses: 'artis3n/ansible_galaxy_collection@v2'
        with:
          api_key: '${{ secrets.GALAXY_API_KEY }}'
